# Generated by Django 4.2.5 on 2023-12-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('soft_skills', models.TextField()),
                ('salary_range', models.CharField(max_length=255)),
                ('application_deadline', models.DateField(default=None)),
                ('post_status', models.CharField(max_length=255)),
                ('approval', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('viewed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
        migrations.CreateModel(
            name='SaveJobPosts',
            fields=[
                ('save_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerRegister',
            fields=[
                ('job_seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('street_address_line1', models.CharField(max_length=255)),
                ('street_address_line2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('highest_qualification', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(default=0.0)),
                ('resume', models.CharField(max_length=255)),
                ('experience_type', models.CharField(default='fresher', max_length=255)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login'),
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('job_applications_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(max_length=255)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegister',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('profile', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('license_no', models.PositiveBigIntegerField(default=0)),
                ('business_license', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
    ]
