# Generated by Django 4.2.5 on 2023-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegister',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('email', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('license_no', models.PositiveBigIntegerField(default=0)),
                ('business_license', models.CharField(max_length=255)),
                ('company_password', models.CharField(max_length=255)),
                ('confirm_companyPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
