# Generated by Django 4.2.6 on 2023-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregister',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerregister',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
