# Generated by Django 4.2.6 on 2023-11-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('application_deadline', models.DateField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
    ]
