# Generated by Django 4.2.6 on 2024-02-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
