# Generated by Django 4.2.6 on 2024-02-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_examquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestions',
            name='correct_ans',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestions',
            name='exam_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.examform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestions',
            name='no_of_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestions',
            name='option_a',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestions',
            name='option_b',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestions',
            name='option_c',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='option_d',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='question_desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
