# Generated by Django 4.2.5 on 2024-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employeeregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForm',
            fields=[
                ('exam_create_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('negative_marking_percentage', models.IntegerField()),
                ('display_countdown', models.BooleanField()),
            ],
        ),
    ]
