# Generated by Django 4.2.6 on 2024-02-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_examquestions_correct_ans_examquestions_exam_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestions',
            old_name='exam_create',
            new_name='exam_create_id',
        ),
    ]
