# Generated by Django 4.2.6 on 2024-03-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_examform_markseach_examquestions_correct_ans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('answered', models.CharField(max_length=255, null=True)),
                ('correct_ans', models.CharField(max_length=255, null=True)),
                ('score', models.IntegerField()),
                ('exam_create_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examform')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.login')),
            ],
        ),
    ]
