# Generated by Django 4.2.6 on 2024-02-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_examform_display_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_questions', models.IntegerField()),
                ('question_desc', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255, null=True)),
                ('option_d', models.CharField(max_length=255, null=True)),
                ('correct_ans', models.CharField(max_length=255)),
                ('exam_create_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examform')),
            ],
        ),
    ]
