# Generated by Django 4.2.6 on 2024-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_examscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscores',
            name='time_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examscores',
            name='score',
            field=models.FloatField(),
        ),
    ]
