# Generated by Django 4.2.6 on 2024-02-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_examquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestions',
            name='exam_create_id',
        ),
    ]
